spring:
  profiles:
    active: local
    include:
      - dubbo
      - mysql
      - kafka
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2
    max-connections: 20000

server:
  port: 9063

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql