#通用配置
dubbo:
#  scan:
#    base-packages: com.tuanche.web.service.impl
  application:
    name: direct-selling-web
    id: direct-selling-web
  protocol:
    name: dubbo
    port: 22895
  registry:
    check: false
  consumer:
    timeout: 20000
    check: false
    filter: tracing
---
# dev
spring:
  profiles: dev
dubbo:
  registry:
#    address: 172.16.70.112:2181,172.16.70.113:2181,172.16.70.114:2181
    address: 172.16.5.90:2181,172.16.5.90:2182,172.16.5.90:2183
#    address: 172.16.12.42:2181,172.16.12.42:2182,172.16.12.42:2183
    protocol: zookeeper

---
# test
spring:
  profiles: test
dubbo:
  registry:
    address: zookeeper.tuanche.com:2181,zookeeper.tuanche.com:2182,zookeeper.tuanche.com:2183
    protocol: zookeeper

---
# pre
spring:
  profiles: pre
dubbo:
  registry:
    address: zookeeper.tuanche.com:2181,zookeeper.tuanche.com:2182,zookeeper.tuanche.com:2183
    protocol: zookeeper

---
# prod
spring:
  profiles: prod
dubbo:
  registry:
    address: zk103.srv.other:2181,zk105.srv.other:2181,zk152.srv.other:2181
    protocol: zookeeper