spring:
  profiles:
    active: dev
    include:
      - dubbo
      - kafka
  resources:
    static-locations: classpath:/templates,classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

server:
  port: 80
  max-http-header-size: 4048576
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
